refactor/GRW-602-integrate QuoteCart API on Campaign code management
HedvigInsurance/web-onboarding pull request #709
Opened 2021-12-09 11:00 UTC by guilhermespopolin

## Disclaimer

This is opened as a draft because it's a living thing. It depends on #701 so it can benefit of the changes made on `Offer` page and it's going to be impacted by #705 since it's based on components that renders `DiscountTag`.

## What?

Following the same pattern used during the whole _integrate QuoteCart API_ work, I'm making the changes by adding cloning the components that would be affected by the transition and change them so they use the new API. In this case, the cloned components are: 

`src/client/pages/OfferNew/Introduction/index.tsx` --> `src/client/pages/OfferNew/Introduction/Introduction.tsx`
`src/client/pages/OfferNew/Introduction/Sidebar/index.tsx` --> `src/client/pages/OfferNew/Introduction/Sidebar/Sidebar.tsx`
`src/client/pages/OfferNew/Introduction/Sidebar/DiscountCodeModal.tsx` --> `src/client/pages/OfferNew/Introduction/Sidebar/CampaignCodeModal.tsx`

The changes:

- `Introduction` and `Sidebar` now accepts a `quoteCartId`. `Introduction` gets it from `Offer` page and them passes it down to `Sidebar` who, among other things, uses it to get and render  `campaign` info using `QuoteCart API`
- `Sidebar` make usage of mutations to add/remove campaign codes. Those mutations are part of the new API.
- `Sidebar` renders a `CampaignCodeModal` component and provide to it a callback to be called during the attempt of adding a campaign code.
- Some renaming were made as requested so _campaign (code)_ term is used rather then _discount/redeem_.

## Why?

- The new API should be used on Campaign during code management 

**Ticket(s): [GRW-602](https://hedvig.atlassian.net/browse/GRW-602)**

2021-12-14 08:15 UTC, robinandeer requested changes
Let's avoid mixing existing and quote cart API components.

Prefer putting the new `Sidebar`/`Introduction` under `Offer` instead of `OfferNew` :)

2021-12-14 10:08 UTC, mehdielket commented on src/client/pages/Offer/index.tsx
> +import { Introduction } from '../OfferNew/Introduction/Introduction'
You can take a look at my Details Modal PR for reference on how we approached duplicating components

2021-12-14 12:41 UTC, guilhermespopolin commented on src/client/pages/Offer/index.tsx
> +import { Introduction } from '../OfferNew/Introduction/Introduction'
Do you mean place new `Introduction` inside `Offer/Introduction/index.tsx`?

2021-12-15 10:56 UTC, closed without merging

2021-12-15 10:57 UTC, guilhermespopolin commented
I closing this one and opening a new one: #718 due a renaming of the branch.