bugfix/GRW-772/Add voucher Code
HedvigInsurance/web-onboarding pull request #799
Opened 2022-02-03 15:43 UTC by dendoesit

## What?

Fix the add voucher code button on the offer page. Reported in the quote cart testing session. 

## Why?

I believe this breaks after the new input-fields PR and I think it is easier to roll forward than roll back. There was some code scouting to be done in the file but I did not want to block the release. 

## Screenshots / recordings 
Now if you type something the button becomes clickable. 
![image](https://user-images.githubusercontent.com/63097139/152376066-afa1d8df-c586-4e43-a85e-78014047da0d.png)

2022-02-04 15:11 UTC, robinandeer reviewed
Would this be the same problem as in #798? Then we just need to pass a "name" attribute and it will work, no?

also => do you wanna make the changes for the new quote cart offer page as well? 🙏

2022-02-04 18:17 UTC, guilhermespopolin requested changes
As @robinandeer has mentioned, it would be great if you also change `pages/Offer/Introduction/Sidebar/CampaignCodeModal.tsx` file.

2022-02-04 18:17 UTC, guilhermespopolin commented on src/client/pages/OfferNew/Introduction/Sidebar/DiscountCodeModal.tsx
>                  label={textKeys.SIDEBAR_ADD_DISCOUNT_CELL_LABEL()}
```suggestion
          {({ getFieldProps, values, touched, errors, isSubmitting }) => (
            <Form>
              <InputField
                label={textKeys.SIDEBAR_ADD_DISCOUNT_CELL_LABEL()}
                placeholder={textKeys.SIDEBAR_ADD_DISCOUNT_CELL_PLACEHOLDER()}
                  type="text"
                  touched={touched.code}
                  errors={errors.code ? textKeys[errors.code]() : ''}
                  {...getFieldProps('code')}
                />
                  <Footer>
                    <Button
                      type="submit"
                      fullWidth
                      disabled={!values.code.trim() || isSubmitting}
                    >
                      {textKeys.SIDEBAR_ADD_DISCOUNT_BUTTON()}
                    </Button>
                  </Footer>
              </Form>
            )}}
```

2022-02-07 09:23 UTC, guilhermespopolin approved these changes
👍🏻

2022-02-07 09:25 UTC, merged